### ISSUE TITLE
[feat] 친구 페이지

### ISSUE THREAD

**Issue by choiseoji** [BeautiPong/beautipong-front#27]
## 설명
- 친구 페이지 구현
- 친구 리스트 보여주기
- 친구 추가 및 수락
- 채팅 화면

## TODO
- [x] 친구 리스트 컴포넌트
- [x] 친구 요청 컴포넌트
- [x] 채팅방 컴포넌트
- [x] 기본 화면 구현
