### ISSUE TITLE
[feat] 친구 페이지 디테일

### ISSUE THREAD

**Issue by choiseoji** [BeautiPong/beautipong-front#67]
## 설명
- 친구 온라인/오프라인 상태 반영
- 친구 정보 채팅창에 반영 (n승 n패)
- 커서 올려두면 색 변하도록 (친구 리스트에서)
- 친구 요청 도착했을 때 화면 조금 이상함

## TODO
- [x] 온라인/오프라인 css 따로 만들기
- [x] 친구 정보 가져와서 채팅창에 보여주기
- [x] 커서 설정
- [x] 친구 요청 화면 사이즈 맞추기

- [x] 친구함 차단함 구분
- [x] 친구 목록 그림자 빼기
- [ ] 호버했을 때 회색선 제거
- [x] 친구 검색 에러......
- [x] 친구 추가 버튼 오른쪽에 고정
